# Generated by Django 3.1.1 on 2021-11-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='buy_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sell_price',
            field=models.FloatField(),
        ),
    ]
