# Generated by Django 4.1 on 2022-08-09 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211109_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='company',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='group',
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(choices=[('capsule', 'Capsule'), ('tablet', 'Tablet'), ('syrup', 'Syrup'), ('injection', 'Injection')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='medicine',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.generic'),
            preserve_default=False,
        ),
    ]
