# Generated by Django 4.1 on 2023-06-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_remove_medicine_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericvalues',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_category', to='shop.genericcategory'),
        ),
    ]
