# Generated by Django 4.1 on 2023-06-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_genericvalues_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='jjddfjd.jpg', upload_to='category'),
            preserve_default=False,
        ),
    ]
